# Generated by Django 4.2.2 on 2023-07-01 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_purchase',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2023, 9, 29)),
        ),
    ]
