# Generated by Django 3.2.19 on 2023-06-09 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(default=datetime.date(2023, 9, 7))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.customer')),
                ('loyaltyProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.loyaltyprogram')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.product')),
            ],
        ),
        migrations.DeleteModel(
            name='SalesMaster',
        ),
    ]
