# Generated by Django 4.2.2 on 2023-07-02 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_rewardpoints_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_purchase',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2023, 9, 30)),
        ),
        migrations.AlterField(
            model_name='rewardpoints',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2023, 9, 30)),
        ),
    ]
